# Generated by Django 3.0.5 on 2021-06-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='industry',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='mcap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
