# Generated by Django 3.0.5 on 2021-06-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20210625_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
