# Generated by Django 3.0.5 on 2021-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_auto_20210625_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='videourl',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
